// <auto-generated />
using System;
using Confitec.TestePratico.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Confitec.TestePratico.Infra.Data.Migrations
{
    [DbContext(typeof(ConfitecContext))]
    [Migration("20211121200422_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Confitec.TestePratico.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(2011, 7, 6, 0, 24, 4, 635, DateTimeKind.Local).AddTicks(673),
                            Email = "caua_costa68@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Maria Alice",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(2003, 8, 14, 17, 31, 39, 826, DateTimeKind.Local).AddTicks(8279),
                            Email = "melissa.saraiva@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Miguel",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = new DateTime(2014, 9, 6, 11, 0, 32, 628, DateTimeKind.Local).AddTicks(2371),
                            Email = "pablo_xavier@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Vitor",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 4,
                            DataNascimento = new DateTime(2020, 8, 10, 13, 39, 55, 609, DateTimeKind.Local).AddTicks(4949),
                            Email = "tertuliano.franco61@gmail.com",
                            Escolaridade = 3,
                            Nome = "Rafaela",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 5,
                            DataNascimento = new DateTime(2012, 6, 7, 12, 51, 45, 701, DateTimeKind.Local).AddTicks(5893),
                            Email = "pietro.braga@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Anthony",
                            Sobrenome = "Franco"
                        },
                        new
                        {
                            Id = 6,
                            DataNascimento = new DateTime(2020, 11, 23, 5, 2, 19, 633, DateTimeKind.Local).AddTicks(8875),
                            Email = "liz.carvalho@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Mariana",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 7,
                            DataNascimento = new DateTime(2013, 8, 31, 20, 30, 28, 444, DateTimeKind.Local).AddTicks(4958),
                            Email = "kleber49@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Ígor",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 8,
                            DataNascimento = new DateTime(2016, 2, 18, 5, 6, 38, 567, DateTimeKind.Local).AddTicks(5093),
                            Email = "marialuiza69@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Ana Júlia",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 9,
                            DataNascimento = new DateTime(2010, 8, 31, 17, 48, 22, 214, DateTimeKind.Local).AddTicks(7443),
                            Email = "mariahelena.santos30@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Ricardo",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 10,
                            DataNascimento = new DateTime(2010, 8, 14, 11, 32, 30, 247, DateTimeKind.Local).AddTicks(2556),
                            Email = "karla_costa18@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Luiza",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 11,
                            DataNascimento = new DateTime(2021, 5, 24, 11, 7, 49, 175, DateTimeKind.Local).AddTicks(8908),
                            Email = "marcia.silva47@live.com",
                            Escolaridade = 2,
                            Nome = "Sarah",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 12,
                            DataNascimento = new DateTime(2018, 12, 4, 22, 32, 37, 21, DateTimeKind.Local).AddTicks(8899),
                            Email = "paula_barros@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Hélio",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 13,
                            DataNascimento = new DateTime(2013, 7, 18, 16, 9, 44, 439, DateTimeKind.Local).AddTicks(8902),
                            Email = "giovanna.pereira59@live.com",
                            Escolaridade = 2,
                            Nome = "Talita",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 14,
                            DataNascimento = new DateTime(2018, 12, 27, 13, 40, 59, 352, DateTimeKind.Local).AddTicks(7642),
                            Email = "mariaclara83@live.com",
                            Escolaridade = 4,
                            Nome = "Enzo",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 15,
                            DataNascimento = new DateTime(2004, 8, 25, 19, 0, 23, 117, DateTimeKind.Local).AddTicks(3115),
                            Email = "liz58@live.com",
                            Escolaridade = 2,
                            Nome = "Vitória",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 16,
                            DataNascimento = new DateTime(2021, 2, 4, 8, 28, 28, 31, DateTimeKind.Local).AddTicks(9890),
                            Email = "alexandre1@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Esther",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 17,
                            DataNascimento = new DateTime(2016, 7, 31, 13, 19, 31, 297, DateTimeKind.Local).AddTicks(9815),
                            Email = "nubia_silva8@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Júlio César",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 18,
                            DataNascimento = new DateTime(2009, 5, 7, 13, 43, 42, 501, DateTimeKind.Local).AddTicks(3968),
                            Email = "victor39@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Matheus",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 19,
                            DataNascimento = new DateTime(2007, 8, 12, 23, 38, 6, 886, DateTimeKind.Local).AddTicks(7691),
                            Email = "antonio0@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Tertuliano",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 20,
                            DataNascimento = new DateTime(2020, 3, 24, 19, 21, 18, 615, DateTimeKind.Local).AddTicks(3567),
                            Email = "emanuelly.moreira77@live.com",
                            Escolaridade = 3,
                            Nome = "Maria Eduarda",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 21,
                            DataNascimento = new DateTime(2018, 4, 3, 1, 29, 11, 186, DateTimeKind.Local).AddTicks(7148),
                            Email = "marli_nogueira46@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Meire",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 22,
                            DataNascimento = new DateTime(2008, 12, 8, 18, 24, 30, 38, DateTimeKind.Local).AddTicks(7060),
                            Email = "vitoria.silva57@live.com",
                            Escolaridade = 2,
                            Nome = "Célia",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 23,
                            DataNascimento = new DateTime(2016, 3, 12, 9, 22, 0, 539, DateTimeKind.Local).AddTicks(9370),
                            Email = "helio19@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Emanuelly",
                            Sobrenome = "Franco"
                        },
                        new
                        {
                            Id = 24,
                            DataNascimento = new DateTime(2015, 10, 1, 2, 5, 37, 838, DateTimeKind.Local).AddTicks(4587),
                            Email = "noah_martins67@gmail.com",
                            Escolaridade = 4,
                            Nome = "Lorena",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 25,
                            DataNascimento = new DateTime(2003, 11, 27, 11, 26, 21, 299, DateTimeKind.Local).AddTicks(9901),
                            Email = "murilo66@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Sara",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 26,
                            DataNascimento = new DateTime(2012, 4, 17, 3, 40, 30, 434, DateTimeKind.Local).AddTicks(4984),
                            Email = "isabela_oliveira98@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Bruna",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 27,
                            DataNascimento = new DateTime(2007, 12, 12, 18, 40, 55, 278, DateTimeKind.Local).AddTicks(6530),
                            Email = "pedrohenrique95@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Samuel",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 28,
                            DataNascimento = new DateTime(2010, 9, 16, 14, 46, 41, 695, DateTimeKind.Local).AddTicks(4988),
                            Email = "pablo.nogueira@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Benício",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 29,
                            DataNascimento = new DateTime(2009, 9, 7, 19, 26, 54, 165, DateTimeKind.Local).AddTicks(4272),
                            Email = "carlos_macedo@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Alessandra",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 30,
                            DataNascimento = new DateTime(2014, 3, 1, 19, 19, 3, 306, DateTimeKind.Local).AddTicks(523),
                            Email = "anthony79@gmail.com",
                            Escolaridade = 4,
                            Nome = "Norberto",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 31,
                            DataNascimento = new DateTime(2018, 10, 14, 4, 20, 24, 571, DateTimeKind.Local).AddTicks(347),
                            Email = "anthony.nogueira56@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Márcia",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 32,
                            DataNascimento = new DateTime(2011, 8, 25, 5, 45, 36, 884, DateTimeKind.Local).AddTicks(2033),
                            Email = "silvia.franco80@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Daniel",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 33,
                            DataNascimento = new DateTime(2002, 3, 28, 11, 57, 10, 599, DateTimeKind.Local).AddTicks(9139),
                            Email = "gustavo.silva98@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Maitê",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 34,
                            DataNascimento = new DateTime(2018, 1, 30, 11, 24, 18, 14, DateTimeKind.Local).AddTicks(847),
                            Email = "roberto.moreira@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Fabrícia",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 35,
                            DataNascimento = new DateTime(2017, 12, 21, 19, 31, 19, 497, DateTimeKind.Local).AddTicks(6300),
                            Email = "suelen.franco@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Pablo",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 36,
                            DataNascimento = new DateTime(2006, 3, 2, 15, 13, 9, 464, DateTimeKind.Local).AddTicks(8242),
                            Email = "lorena_albuquerque@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Miguel",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 37,
                            DataNascimento = new DateTime(2009, 11, 20, 2, 50, 54, 201, DateTimeKind.Local).AddTicks(8215),
                            Email = "lorenzo88@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Eduarda",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 38,
                            DataNascimento = new DateTime(2016, 2, 26, 12, 36, 45, 641, DateTimeKind.Local).AddTicks(2069),
                            Email = "rebeca_souza@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Ladislau",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 39,
                            DataNascimento = new DateTime(2008, 2, 23, 18, 46, 40, 985, DateTimeKind.Local).AddTicks(204),
                            Email = "gabriel.braga16@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Samuel",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 40,
                            DataNascimento = new DateTime(2009, 10, 31, 15, 56, 4, 743, DateTimeKind.Local).AddTicks(4329),
                            Email = "vicente92@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Júlia",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 41,
                            DataNascimento = new DateTime(2014, 8, 12, 5, 46, 18, 823, DateTimeKind.Local).AddTicks(2180),
                            Email = "gael52@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Enzo",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 42,
                            DataNascimento = new DateTime(2021, 3, 15, 1, 27, 19, 985, DateTimeKind.Local).AddTicks(8738),
                            Email = "eloa.martins@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Eloá",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 43,
                            DataNascimento = new DateTime(2013, 10, 10, 0, 30, 0, 573, DateTimeKind.Local).AddTicks(7668),
                            Email = "lorenzo.reis65@gmail.com",
                            Escolaridade = 2,
                            Nome = "Isabel",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 44,
                            DataNascimento = new DateTime(2006, 8, 11, 2, 22, 24, 312, DateTimeKind.Local).AddTicks(3367),
                            Email = "warley93@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Esther",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 45,
                            DataNascimento = new DateTime(2019, 7, 6, 0, 49, 0, 374, DateTimeKind.Local).AddTicks(8523),
                            Email = "alessandro.franco50@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Rebeca",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 46,
                            DataNascimento = new DateTime(2015, 2, 27, 8, 3, 50, 609, DateTimeKind.Local).AddTicks(4286),
                            Email = "joaquim.franco79@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Vitória",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 47,
                            DataNascimento = new DateTime(2014, 4, 17, 18, 46, 8, 863, DateTimeKind.Local).AddTicks(645),
                            Email = "antonella89@gmail.com",
                            Escolaridade = 2,
                            Nome = "Sophia",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 48,
                            DataNascimento = new DateTime(2007, 4, 11, 1, 58, 44, 764, DateTimeKind.Local).AddTicks(3427),
                            Email = "morgana.oliveira78@live.com",
                            Escolaridade = 1,
                            Nome = "Fábio",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 49,
                            DataNascimento = new DateTime(2010, 9, 14, 15, 57, 15, 659, DateTimeKind.Local).AddTicks(1871),
                            Email = "igor.batista96@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Karla",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 50,
                            DataNascimento = new DateTime(2004, 2, 12, 11, 53, 4, 925, DateTimeKind.Local).AddTicks(912),
                            Email = "yago_melo@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Leonardo",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 51,
                            DataNascimento = new DateTime(2010, 1, 12, 10, 33, 47, 468, DateTimeKind.Local).AddTicks(925),
                            Email = "livia_barros43@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Samuel",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 52,
                            DataNascimento = new DateTime(2004, 2, 13, 2, 14, 56, 286, DateTimeKind.Local).AddTicks(296),
                            Email = "mariaalice57@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Ana Júlia",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 53,
                            DataNascimento = new DateTime(2005, 2, 14, 7, 47, 49, 729, DateTimeKind.Local).AddTicks(9365),
                            Email = "cesar.barros@gmail.com",
                            Escolaridade = 4,
                            Nome = "Aline",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 54,
                            DataNascimento = new DateTime(2010, 9, 14, 3, 26, 24, 142, DateTimeKind.Local).AddTicks(8808),
                            Email = "marina.batista@live.com",
                            Escolaridade = 2,
                            Nome = "Frederico",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 55,
                            DataNascimento = new DateTime(2020, 8, 7, 15, 44, 45, 873, DateTimeKind.Local).AddTicks(1759),
                            Email = "enzo_reis@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Washington",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 56,
                            DataNascimento = new DateTime(2019, 2, 10, 17, 15, 54, 932, DateTimeKind.Local).AddTicks(2908),
                            Email = "pedrohenrique3@live.com",
                            Escolaridade = 3,
                            Nome = "Yuri",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 57,
                            DataNascimento = new DateTime(2013, 4, 20, 18, 42, 59, 373, DateTimeKind.Local).AddTicks(1710),
                            Email = "mercia.oliveira88@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Isadora",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 58,
                            DataNascimento = new DateTime(2005, 7, 20, 3, 8, 48, 604, DateTimeKind.Local).AddTicks(9213),
                            Email = "livia.martins63@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Miguel",
                            Sobrenome = "Braga"
                        },
                        new
                        {
                            Id = 59,
                            DataNascimento = new DateTime(2009, 8, 8, 16, 18, 21, 455, DateTimeKind.Local).AddTicks(7065),
                            Email = "mariana45@live.com",
                            Escolaridade = 3,
                            Nome = "Márcia",
                            Sobrenome = "Franco"
                        },
                        new
                        {
                            Id = 60,
                            DataNascimento = new DateTime(2010, 6, 1, 9, 35, 47, 200, DateTimeKind.Local).AddTicks(8075),
                            Email = "lorraine.martins@live.com",
                            Escolaridade = 2,
                            Nome = "Pietro",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 61,
                            DataNascimento = new DateTime(2019, 9, 7, 14, 6, 6, 677, DateTimeKind.Local).AddTicks(4053),
                            Email = "joaquim_saraiva@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Larissa",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 62,
                            DataNascimento = new DateTime(2007, 5, 17, 8, 18, 44, 111, DateTimeKind.Local).AddTicks(848),
                            Email = "livia.albuquerque10@gmail.com",
                            Escolaridade = 1,
                            Nome = "Beatriz",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 63,
                            DataNascimento = new DateTime(2005, 12, 24, 23, 12, 49, 717, DateTimeKind.Local).AddTicks(9479),
                            Email = "gael9@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Júlia",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 64,
                            DataNascimento = new DateTime(2011, 4, 19, 14, 7, 50, 673, DateTimeKind.Local).AddTicks(1394),
                            Email = "analaura_macedo@gmail.com",
                            Escolaridade = 2,
                            Nome = "Sophia",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 65,
                            DataNascimento = new DateTime(2019, 1, 4, 20, 41, 50, 945, DateTimeKind.Local).AddTicks(9792),
                            Email = "paula37@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Yango",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 66,
                            DataNascimento = new DateTime(2019, 2, 20, 10, 13, 53, 452, DateTimeKind.Local).AddTicks(2149),
                            Email = "paulo.costa@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Alessandra",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 67,
                            DataNascimento = new DateTime(2016, 12, 25, 9, 40, 31, 198, DateTimeKind.Local).AddTicks(3876),
                            Email = "esther_franco@gmail.com",
                            Escolaridade = 1,
                            Nome = "Isabelly",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 68,
                            DataNascimento = new DateTime(2016, 10, 13, 15, 55, 24, 993, DateTimeKind.Local).AddTicks(8421),
                            Email = "breno_martins30@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Laura",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 69,
                            DataNascimento = new DateTime(2012, 9, 6, 1, 4, 45, 635, DateTimeKind.Local).AddTicks(6600),
                            Email = "analaura.oliveira@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Giovanna",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 70,
                            DataNascimento = new DateTime(2003, 9, 20, 15, 7, 27, 882, DateTimeKind.Local).AddTicks(8688),
                            Email = "sarah.batista29@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Roberto",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 71,
                            DataNascimento = new DateTime(2004, 9, 15, 4, 46, 12, 814, DateTimeKind.Local).AddTicks(4678),
                            Email = "yago_reis6@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Luiza",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 72,
                            DataNascimento = new DateTime(2020, 2, 25, 10, 56, 58, 278, DateTimeKind.Local).AddTicks(4168),
                            Email = "lorenzo_costa@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Warley",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 73,
                            DataNascimento = new DateTime(2007, 11, 12, 8, 59, 47, 416, DateTimeKind.Local).AddTicks(4623),
                            Email = "karla92@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Elisa",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 74,
                            DataNascimento = new DateTime(2009, 9, 17, 11, 37, 9, 779, DateTimeKind.Local).AddTicks(9497),
                            Email = "livia46@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Emanuel",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 75,
                            DataNascimento = new DateTime(2004, 8, 21, 23, 22, 19, 284, DateTimeKind.Local).AddTicks(2616),
                            Email = "eloa90@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Elisa",
                            Sobrenome = "Braga"
                        },
                        new
                        {
                            Id = 76,
                            DataNascimento = new DateTime(2003, 2, 22, 18, 38, 38, 875, DateTimeKind.Local).AddTicks(6411),
                            Email = "enzo.nogueira@gmail.com",
                            Escolaridade = 4,
                            Nome = "Fabrício",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 77,
                            DataNascimento = new DateTime(2020, 5, 23, 22, 39, 6, 903, DateTimeKind.Local).AddTicks(6967),
                            Email = "laura_silva86@live.com",
                            Escolaridade = 4,
                            Nome = "Maria Clara",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 78,
                            DataNascimento = new DateTime(2019, 9, 14, 9, 33, 57, 299, DateTimeKind.Local).AddTicks(6562),
                            Email = "yago.carvalho@gmail.com",
                            Escolaridade = 3,
                            Nome = "Isis",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 79,
                            DataNascimento = new DateTime(2002, 6, 12, 7, 17, 28, 677, DateTimeKind.Local).AddTicks(5359),
                            Email = "marli.carvalho@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Fabiano",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 80,
                            DataNascimento = new DateTime(2003, 11, 26, 5, 11, 21, 114, DateTimeKind.Local).AddTicks(4071),
                            Email = "manuela51@gmail.com",
                            Escolaridade = 4,
                            Nome = "Calebe",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 81,
                            DataNascimento = new DateTime(2006, 3, 1, 13, 45, 15, 817, DateTimeKind.Local).AddTicks(2213),
                            Email = "alice_carvalho@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Margarida",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 82,
                            DataNascimento = new DateTime(2012, 3, 4, 17, 57, 35, 699, DateTimeKind.Local).AddTicks(9945),
                            Email = "nubia_nogueira@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Vicente",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 83,
                            DataNascimento = new DateTime(2020, 12, 28, 21, 59, 18, 872, DateTimeKind.Local).AddTicks(4013),
                            Email = "alessandro99@live.com",
                            Escolaridade = 1,
                            Nome = "Ígor",
                            Sobrenome = "Braga"
                        },
                        new
                        {
                            Id = 84,
                            DataNascimento = new DateTime(2012, 11, 9, 11, 20, 56, 778, DateTimeKind.Local).AddTicks(1524),
                            Email = "lorenzo_costa1@gmail.com",
                            Escolaridade = 1,
                            Nome = "César",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 85,
                            DataNascimento = new DateTime(2015, 6, 15, 17, 1, 15, 633, DateTimeKind.Local).AddTicks(4629),
                            Email = "felicia_batista96@live.com",
                            Escolaridade = 3,
                            Nome = "Larissa",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 86,
                            DataNascimento = new DateTime(2013, 11, 29, 2, 3, 4, 300, DateTimeKind.Local).AddTicks(4486),
                            Email = "nubia_xavier30@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Danilo",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 87,
                            DataNascimento = new DateTime(2011, 6, 20, 7, 34, 32, 211, DateTimeKind.Local).AddTicks(8185),
                            Email = "paula.reis81@live.com",
                            Escolaridade = 4,
                            Nome = "Pietro",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 88,
                            DataNascimento = new DateTime(2006, 11, 19, 15, 30, 8, 346, DateTimeKind.Local).AddTicks(3417),
                            Email = "melissa_santos@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Pietro",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 89,
                            DataNascimento = new DateTime(2021, 3, 5, 22, 35, 36, 163, DateTimeKind.Local).AddTicks(3291),
                            Email = "davilucca_franco36@live.com",
                            Escolaridade = 3,
                            Nome = "Mércia",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 90,
                            DataNascimento = new DateTime(2013, 11, 8, 3, 7, 2, 170, DateTimeKind.Local).AddTicks(403),
                            Email = "davilucca_moreira@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Ricardo",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 91,
                            DataNascimento = new DateTime(2009, 1, 13, 13, 42, 32, 802, DateTimeKind.Local).AddTicks(3876),
                            Email = "silvia46@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Célia",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 92,
                            DataNascimento = new DateTime(2019, 8, 21, 1, 1, 58, 774, DateTimeKind.Local).AddTicks(8214),
                            Email = "isabelly46@live.com",
                            Escolaridade = 3,
                            Nome = "Meire",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 93,
                            DataNascimento = new DateTime(2007, 4, 11, 5, 26, 56, 236, DateTimeKind.Local).AddTicks(6777),
                            Email = "anaclara_franco@gmail.com",
                            Escolaridade = 4,
                            Nome = "Ofélia",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 94,
                            DataNascimento = new DateTime(2009, 1, 5, 18, 22, 45, 796, DateTimeKind.Local).AddTicks(4126),
                            Email = "livia14@gmail.com",
                            Escolaridade = 3,
                            Nome = "Eduardo",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 95,
                            DataNascimento = new DateTime(2017, 12, 23, 22, 5, 11, 886, DateTimeKind.Local).AddTicks(5337),
                            Email = "daniel94@live.com",
                            Escolaridade = 2,
                            Nome = "Roberta",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 96,
                            DataNascimento = new DateTime(2005, 10, 16, 8, 3, 5, 395, DateTimeKind.Local).AddTicks(5065),
                            Email = "bryan_silva14@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Meire",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 97,
                            DataNascimento = new DateTime(2006, 8, 13, 12, 28, 59, 220, DateTimeKind.Local).AddTicks(6768),
                            Email = "salvador.moraes@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Arthur",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 98,
                            DataNascimento = new DateTime(2009, 7, 2, 18, 46, 8, 842, DateTimeKind.Local).AddTicks(8315),
                            Email = "isis_pereira80@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Ana Luiza",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 99,
                            DataNascimento = new DateTime(2021, 8, 10, 9, 44, 54, 525, DateTimeKind.Local).AddTicks(6573),
                            Email = "gabriel91@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Davi",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 100,
                            DataNascimento = new DateTime(2021, 5, 1, 20, 33, 10, 83, DateTimeKind.Local).AddTicks(7362),
                            Email = "isabella8@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Antonella",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 101,
                            DataNascimento = new DateTime(2015, 5, 3, 23, 52, 17, 350, DateTimeKind.Local).AddTicks(3573),
                            Email = "gubio94@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Marina",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 102,
                            DataNascimento = new DateTime(2017, 1, 28, 5, 49, 24, 664, DateTimeKind.Local).AddTicks(9303),
                            Email = "dalila_macedo56@live.com",
                            Escolaridade = 2,
                            Nome = "Nataniel",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 103,
                            DataNascimento = new DateTime(2015, 10, 1, 5, 27, 30, 473, DateTimeKind.Local).AddTicks(7983),
                            Email = "vitor_saraiva@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Alícia",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 104,
                            DataNascimento = new DateTime(2013, 3, 3, 6, 34, 11, 159, DateTimeKind.Local).AddTicks(8570),
                            Email = "cecilia.souza@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Lara",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 105,
                            DataNascimento = new DateTime(2015, 8, 8, 15, 25, 22, 59, DateTimeKind.Local).AddTicks(2728),
                            Email = "lucas.batista83@gmail.com",
                            Escolaridade = 3,
                            Nome = "Arthur",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 106,
                            DataNascimento = new DateTime(2007, 11, 14, 19, 22, 11, 629, DateTimeKind.Local).AddTicks(1735),
                            Email = "yasmin.franco@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Paula",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 107,
                            DataNascimento = new DateTime(2019, 5, 20, 15, 30, 7, 666, DateTimeKind.Local).AddTicks(5595),
                            Email = "isaac20@live.com",
                            Escolaridade = 2,
                            Nome = "Júlio",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 108,
                            DataNascimento = new DateTime(2004, 12, 2, 22, 46, 26, 319, DateTimeKind.Local).AddTicks(4333),
                            Email = "felix_reis34@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Hélio",
                            Sobrenome = "Braga"
                        },
                        new
                        {
                            Id = 109,
                            DataNascimento = new DateTime(2002, 1, 20, 12, 44, 35, 532, DateTimeKind.Local).AddTicks(6396),
                            Email = "breno.franco@live.com",
                            Escolaridade = 4,
                            Nome = "Heitor",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 110,
                            DataNascimento = new DateTime(2020, 5, 1, 16, 26, 42, 272, DateTimeKind.Local).AddTicks(5873),
                            Email = "pedrohenrique47@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Luiza",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 111,
                            DataNascimento = new DateTime(2005, 5, 7, 8, 20, 40, 310, DateTimeKind.Local).AddTicks(8180),
                            Email = "yasmin18@live.com",
                            Escolaridade = 2,
                            Nome = "Deneval",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 112,
                            DataNascimento = new DateTime(2008, 6, 5, 17, 13, 7, 610, DateTimeKind.Local).AddTicks(1873),
                            Email = "analaura.moreira53@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Meire",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 113,
                            DataNascimento = new DateTime(2015, 6, 24, 19, 13, 22, 81, DateTimeKind.Local).AddTicks(9052),
                            Email = "esther_costa@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Júlio César",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 114,
                            DataNascimento = new DateTime(2019, 9, 11, 10, 38, 49, 599, DateTimeKind.Local).AddTicks(661),
                            Email = "larissa_moraes@gmail.com",
                            Escolaridade = 2,
                            Nome = "Márcia",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 115,
                            DataNascimento = new DateTime(2012, 5, 6, 15, 5, 5, 69, DateTimeKind.Local).AddTicks(8600),
                            Email = "warley50@live.com",
                            Escolaridade = 3,
                            Nome = "Samuel",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 116,
                            DataNascimento = new DateTime(2010, 2, 19, 20, 5, 59, 581, DateTimeKind.Local).AddTicks(3251),
                            Email = "analuiza_franco@gmail.com",
                            Escolaridade = 1,
                            Nome = "Ana Laura",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 117,
                            DataNascimento = new DateTime(2016, 7, 28, 22, 35, 18, 568, DateTimeKind.Local).AddTicks(9571),
                            Email = "yuri_xavier@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Henrique",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 118,
                            DataNascimento = new DateTime(2011, 5, 9, 15, 27, 49, 588, DateTimeKind.Local).AddTicks(260),
                            Email = "janaina87@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Antonella",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 119,
                            DataNascimento = new DateTime(2014, 1, 16, 11, 28, 23, 800, DateTimeKind.Local).AddTicks(7775),
                            Email = "manuela.moreira@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Ana Clara",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 120,
                            DataNascimento = new DateTime(2007, 4, 16, 3, 23, 14, 761, DateTimeKind.Local).AddTicks(5628),
                            Email = "elisa.martins@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Sophia",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 121,
                            DataNascimento = new DateTime(2019, 7, 31, 17, 0, 54, 791, DateTimeKind.Local).AddTicks(9658),
                            Email = "gubio76@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Larissa",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 122,
                            DataNascimento = new DateTime(2003, 10, 10, 2, 5, 54, 540, DateTimeKind.Local).AddTicks(8028),
                            Email = "yasmin31@gmail.com",
                            Escolaridade = 3,
                            Nome = "Feliciano",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 123,
                            DataNascimento = new DateTime(2012, 6, 30, 7, 35, 11, 564, DateTimeKind.Local).AddTicks(8297),
                            Email = "analuiza74@live.com",
                            Escolaridade = 2,
                            Nome = "Rebeca",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 124,
                            DataNascimento = new DateTime(2019, 2, 7, 15, 15, 26, 237, DateTimeKind.Local).AddTicks(803),
                            Email = "isabella_batista@live.com",
                            Escolaridade = 4,
                            Nome = "Júlio",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 125,
                            DataNascimento = new DateTime(2008, 5, 11, 7, 11, 15, 814, DateTimeKind.Local).AddTicks(2848),
                            Email = "gabriel_souza54@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Lorraine",
                            Sobrenome = "Franco"
                        },
                        new
                        {
                            Id = 126,
                            DataNascimento = new DateTime(2004, 6, 27, 1, 49, 41, 486, DateTimeKind.Local).AddTicks(2349),
                            Email = "mercia.saraiva@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Yasmin",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 127,
                            DataNascimento = new DateTime(2003, 11, 4, 12, 2, 59, 195, DateTimeKind.Local).AddTicks(918),
                            Email = "sophia.albuquerque60@bol.com.br",
                            Escolaridade = 2,
                            Nome = "Benício",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 128,
                            DataNascimento = new DateTime(2006, 12, 29, 9, 17, 24, 800, DateTimeKind.Local).AddTicks(5801),
                            Email = "bryan.albuquerque94@gmail.com",
                            Escolaridade = 3,
                            Nome = "Heloísa",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 129,
                            DataNascimento = new DateTime(2005, 7, 27, 23, 41, 40, 63, DateTimeKind.Local).AddTicks(5881),
                            Email = "caua76@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Hugo",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 130,
                            DataNascimento = new DateTime(2013, 3, 11, 14, 47, 44, 270, DateTimeKind.Local).AddTicks(5047),
                            Email = "anaclara_pereira@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Sophia",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 131,
                            DataNascimento = new DateTime(2014, 2, 27, 14, 50, 22, 140, DateTimeKind.Local).AddTicks(1460),
                            Email = "yango.albuquerque@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Ana Clara",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 132,
                            DataNascimento = new DateTime(2016, 8, 10, 15, 12, 46, 85, DateTimeKind.Local).AddTicks(4712),
                            Email = "yago_carvalho17@gmail.com",
                            Escolaridade = 3,
                            Nome = "Ana Clara",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 133,
                            DataNascimento = new DateTime(2016, 4, 3, 14, 0, 27, 537, DateTimeKind.Local).AddTicks(6961),
                            Email = "anthony.carvalho@gmail.com",
                            Escolaridade = 2,
                            Nome = "Cauã",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 134,
                            DataNascimento = new DateTime(2020, 1, 22, 0, 36, 47, 997, DateTimeKind.Local).AddTicks(1398),
                            Email = "luiza_moreira43@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Alessandro",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 135,
                            DataNascimento = new DateTime(2005, 11, 3, 19, 35, 7, 195, DateTimeKind.Local).AddTicks(5442),
                            Email = "rafaela_moraes@gmail.com",
                            Escolaridade = 4,
                            Nome = "Théo",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 136,
                            DataNascimento = new DateTime(2011, 6, 23, 20, 44, 57, 156, DateTimeKind.Local).AddTicks(9846),
                            Email = "leonardo.oliveira78@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Yango",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 137,
                            DataNascimento = new DateTime(2018, 2, 24, 0, 13, 13, 235, DateTimeKind.Local).AddTicks(1858),
                            Email = "eloa64@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Isabela",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 138,
                            DataNascimento = new DateTime(2003, 9, 26, 5, 53, 3, 959, DateTimeKind.Local).AddTicks(9296),
                            Email = "rebeca.carvalho@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Júlia",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 139,
                            DataNascimento = new DateTime(2005, 3, 4, 10, 51, 29, 687, DateTimeKind.Local).AddTicks(8934),
                            Email = "antonio29@live.com",
                            Escolaridade = 4,
                            Nome = "Tertuliano",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 140,
                            DataNascimento = new DateTime(2006, 12, 7, 1, 8, 55, 546, DateTimeKind.Local).AddTicks(8124),
                            Email = "felipe51@live.com",
                            Escolaridade = 2,
                            Nome = "Maria Eduarda",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 141,
                            DataNascimento = new DateTime(2012, 3, 10, 17, 30, 7, 515, DateTimeKind.Local).AddTicks(4831),
                            Email = "frederico43@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Maria Cecília",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 142,
                            DataNascimento = new DateTime(2016, 5, 29, 10, 27, 24, 689, DateTimeKind.Local).AddTicks(2519),
                            Email = "nubia.moraes16@gmail.com",
                            Escolaridade = 3,
                            Nome = "Maria Clara",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 143,
                            DataNascimento = new DateTime(2001, 12, 26, 18, 37, 50, 425, DateTimeKind.Local).AddTicks(5883),
                            Email = "eduardo_moreira@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Roberta",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 144,
                            DataNascimento = new DateTime(2010, 3, 22, 9, 43, 53, 843, DateTimeKind.Local).AddTicks(4120),
                            Email = "marcela.saraiva@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Vicente",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 145,
                            DataNascimento = new DateTime(2002, 12, 3, 0, 14, 13, 343, DateTimeKind.Local).AddTicks(3945),
                            Email = "benjamin.carvalho@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Sara",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 146,
                            DataNascimento = new DateTime(2012, 11, 6, 15, 2, 42, 206, DateTimeKind.Local).AddTicks(9577),
                            Email = "larissa47@live.com",
                            Escolaridade = 3,
                            Nome = "Leonardo",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 147,
                            DataNascimento = new DateTime(2010, 3, 15, 23, 23, 16, 602, DateTimeKind.Local).AddTicks(5530),
                            Email = "vitor_silva@gmail.com",
                            Escolaridade = 2,
                            Nome = "Cecília",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 148,
                            DataNascimento = new DateTime(2016, 12, 24, 11, 17, 33, 275, DateTimeKind.Local).AddTicks(4641),
                            Email = "sirineu.nogueira@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Júlio César",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 149,
                            DataNascimento = new DateTime(2005, 7, 28, 7, 0, 7, 915, DateTimeKind.Local).AddTicks(5106),
                            Email = "norberto.saraiva@live.com",
                            Escolaridade = 2,
                            Nome = "Hélio",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 150,
                            DataNascimento = new DateTime(2003, 1, 6, 18, 45, 29, 469, DateTimeKind.Local).AddTicks(3294),
                            Email = "mariaeduarda53@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Leonardo",
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 151,
                            DataNascimento = new DateTime(2018, 8, 19, 14, 10, 41, 200, DateTimeKind.Local).AddTicks(4508),
                            Email = "analuiza.oliveira@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Gabriel",
                            Sobrenome = "Xavier"
                        },
                        new
                        {
                            Id = 152,
                            DataNascimento = new DateTime(2004, 5, 1, 14, 51, 17, 221, DateTimeKind.Local).AddTicks(3710),
                            Email = "lucca_souza64@yahoo.com",
                            Escolaridade = 1,
                            Nome = "Talita",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 153,
                            DataNascimento = new DateTime(2004, 9, 18, 1, 4, 21, 815, DateTimeKind.Local).AddTicks(453),
                            Email = "benjamin_silva94@live.com",
                            Escolaridade = 4,
                            Nome = "Kléber",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 154,
                            DataNascimento = new DateTime(2004, 2, 19, 4, 49, 0, 446, DateTimeKind.Local).AddTicks(8937),
                            Email = "joaopedro_xavier35@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Laura",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 155,
                            DataNascimento = new DateTime(2013, 8, 2, 3, 12, 48, 390, DateTimeKind.Local).AddTicks(2221),
                            Email = "alessandra.braga@hotmail.com",
                            Escolaridade = 3,
                            Nome = "João Lucas",
                            Sobrenome = "Barros"
                        },
                        new
                        {
                            Id = 156,
                            DataNascimento = new DateTime(2016, 4, 27, 21, 57, 32, 6, DateTimeKind.Local).AddTicks(6903),
                            Email = "nubia_batista@live.com",
                            Escolaridade = 1,
                            Nome = "Arthur",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 157,
                            DataNascimento = new DateTime(2015, 1, 29, 17, 33, 34, 249, DateTimeKind.Local).AddTicks(5183),
                            Email = "fabiano_albuquerque21@gmail.com",
                            Escolaridade = 3,
                            Nome = "Suélen",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 158,
                            DataNascimento = new DateTime(2003, 1, 14, 10, 31, 5, 565, DateTimeKind.Local).AddTicks(3639),
                            Email = "norberto_carvalho53@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Caio",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 159,
                            DataNascimento = new DateTime(2019, 9, 22, 23, 43, 33, 934, DateTimeKind.Local).AddTicks(4116),
                            Email = "joaopedro51@gmail.com",
                            Escolaridade = 2,
                            Nome = "Breno",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 160,
                            DataNascimento = new DateTime(2019, 1, 8, 8, 20, 21, 686, DateTimeKind.Local).AddTicks(2990),
                            Email = "julio.reis66@gmail.com",
                            Escolaridade = 3,
                            Nome = "Marina",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 161,
                            DataNascimento = new DateTime(2002, 12, 28, 15, 30, 17, 553, DateTimeKind.Local).AddTicks(3277),
                            Email = "marcela.souza@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Isaac",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 162,
                            DataNascimento = new DateTime(2019, 10, 29, 23, 7, 39, 2, DateTimeKind.Local).AddTicks(9402),
                            Email = "mercia.xavier@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Antônio",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 163,
                            DataNascimento = new DateTime(2020, 4, 23, 12, 8, 25, 920, DateTimeKind.Local).AddTicks(8740),
                            Email = "antonella_martins@live.com",
                            Escolaridade = 1,
                            Nome = "Lívia",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 164,
                            DataNascimento = new DateTime(2021, 3, 16, 16, 26, 3, 128, DateTimeKind.Local).AddTicks(8563),
                            Email = "vitor.oliveira31@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Warley",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 165,
                            DataNascimento = new DateTime(2019, 9, 7, 18, 9, 22, 206, DateTimeKind.Local).AddTicks(6600),
                            Email = "giovanna.reis95@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Antônio",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 166,
                            DataNascimento = new DateTime(2004, 12, 8, 13, 14, 46, 93, DateTimeKind.Local).AddTicks(4920),
                            Email = "alexandre9@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Breno",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 167,
                            DataNascimento = new DateTime(2021, 6, 26, 10, 3, 56, 355, DateTimeKind.Local).AddTicks(7235),
                            Email = "emanuelly_martins@yahoo.com",
                            Escolaridade = 3,
                            Nome = "Maria Clara",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 168,
                            DataNascimento = new DateTime(2010, 12, 24, 13, 36, 47, 866, DateTimeKind.Local).AddTicks(8741),
                            Email = "maria31@gmail.com",
                            Escolaridade = 3,
                            Nome = "Paula",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 169,
                            DataNascimento = new DateTime(2021, 6, 14, 16, 39, 36, 338, DateTimeKind.Local).AddTicks(5619),
                            Email = "lorenzo_carvalho@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Ricardo",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 170,
                            DataNascimento = new DateTime(2005, 11, 15, 15, 15, 32, 430, DateTimeKind.Local).AddTicks(7925),
                            Email = "aline.oliveira@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Danilo",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 171,
                            DataNascimento = new DateTime(2017, 2, 21, 7, 45, 38, 476, DateTimeKind.Local).AddTicks(170),
                            Email = "paula83@live.com",
                            Escolaridade = 2,
                            Nome = "Pedro",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 172,
                            DataNascimento = new DateTime(2002, 5, 3, 2, 8, 26, 808, DateTimeKind.Local).AddTicks(9800),
                            Email = "breno_batista@yahoo.com",
                            Escolaridade = 2,
                            Nome = "Washington",
                            Sobrenome = "Nogueira"
                        },
                        new
                        {
                            Id = 173,
                            DataNascimento = new DateTime(2009, 3, 8, 14, 11, 54, 629, DateTimeKind.Local).AddTicks(872),
                            Email = "benicio45@hotmail.com",
                            Escolaridade = 4,
                            Nome = "Raul",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 174,
                            DataNascimento = new DateTime(2018, 4, 18, 20, 1, 36, 484, DateTimeKind.Local).AddTicks(5550),
                            Email = "benicio_moraes@live.com",
                            Escolaridade = 2,
                            Nome = "Bernardo",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 175,
                            DataNascimento = new DateTime(2016, 9, 9, 15, 2, 16, 640, DateTimeKind.Local).AddTicks(2726),
                            Email = "hugo.batista@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Marli",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 176,
                            DataNascimento = new DateTime(2014, 1, 26, 9, 6, 53, 271, DateTimeKind.Local).AddTicks(1648),
                            Email = "alessandra_moreira28@gmail.com",
                            Escolaridade = 1,
                            Nome = "Heloísa",
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 177,
                            DataNascimento = new DateTime(2021, 6, 1, 2, 35, 13, 144, DateTimeKind.Local).AddTicks(5895),
                            Email = "cesar_albuquerque81@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Larissa",
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 178,
                            DataNascimento = new DateTime(2010, 2, 10, 13, 36, 54, 105, DateTimeKind.Local).AddTicks(5067),
                            Email = "alessandra_pereira@gmail.com",
                            Escolaridade = 4,
                            Nome = "Cecília",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 179,
                            DataNascimento = new DateTime(2009, 12, 26, 11, 44, 2, 145, DateTimeKind.Local).AddTicks(6246),
                            Email = "marina.nogueira@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Antônio",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 180,
                            DataNascimento = new DateTime(2011, 6, 2, 13, 23, 25, 998, DateTimeKind.Local).AddTicks(6701),
                            Email = "helio.carvalho@live.com",
                            Escolaridade = 2,
                            Nome = "Rafael",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 181,
                            DataNascimento = new DateTime(2006, 5, 25, 20, 50, 10, 558, DateTimeKind.Local).AddTicks(2196),
                            Email = "marcelo95@gmail.com",
                            Escolaridade = 4,
                            Nome = "Danilo",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 182,
                            DataNascimento = new DateTime(2005, 9, 18, 8, 38, 19, 657, DateTimeKind.Local).AddTicks(1776),
                            Email = "melissa_macedo@gmail.com",
                            Escolaridade = 4,
                            Nome = "Paulo",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 183,
                            DataNascimento = new DateTime(2020, 1, 19, 20, 4, 39, 917, DateTimeKind.Local).AddTicks(7121),
                            Email = "felicia_moraes0@live.com",
                            Escolaridade = 1,
                            Nome = "Dalila",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 184,
                            DataNascimento = new DateTime(2016, 6, 5, 18, 15, 56, 394, DateTimeKind.Local).AddTicks(5915),
                            Email = "marialuiza_barros@live.com",
                            Escolaridade = 4,
                            Nome = "Melissa",
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 185,
                            DataNascimento = new DateTime(2013, 11, 30, 0, 33, 26, 915, DateTimeKind.Local).AddTicks(7954),
                            Email = "heloisa_melo75@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Isaac",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 186,
                            DataNascimento = new DateTime(2011, 3, 30, 7, 28, 49, 575, DateTimeKind.Local).AddTicks(3840),
                            Email = "lorenzo20@live.com",
                            Escolaridade = 3,
                            Nome = "Rafael",
                            Sobrenome = "Braga"
                        },
                        new
                        {
                            Id = 187,
                            DataNascimento = new DateTime(2018, 1, 13, 16, 32, 39, 909, DateTimeKind.Local).AddTicks(9313),
                            Email = "mariajulia40@bol.com.br",
                            Escolaridade = 3,
                            Nome = "Gúbio",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 188,
                            DataNascimento = new DateTime(2015, 4, 8, 3, 45, 22, 950, DateTimeKind.Local).AddTicks(8146),
                            Email = "feliciano_costa@bol.com.br",
                            Escolaridade = 4,
                            Nome = "Gustavo",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 189,
                            DataNascimento = new DateTime(2006, 10, 1, 15, 35, 7, 841, DateTimeKind.Local).AddTicks(7581),
                            Email = "joana17@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Laura",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 190,
                            DataNascimento = new DateTime(2002, 5, 4, 13, 9, 37, 113, DateTimeKind.Local).AddTicks(6622),
                            Email = "aline_santos87@hotmail.com",
                            Escolaridade = 2,
                            Nome = "Emanuelly",
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 191,
                            DataNascimento = new DateTime(2021, 4, 16, 0, 14, 33, 286, DateTimeKind.Local).AddTicks(7766),
                            Email = "maria.moraes28@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Fabrícia",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 192,
                            DataNascimento = new DateTime(2005, 8, 9, 0, 24, 17, 63, DateTimeKind.Local).AddTicks(1565),
                            Email = "rebeca.franco@gmail.com",
                            Escolaridade = 4,
                            Nome = "Maria Helena",
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 193,
                            DataNascimento = new DateTime(2003, 3, 17, 13, 14, 52, 406, DateTimeKind.Local).AddTicks(2307),
                            Email = "alice26@yahoo.com",
                            Escolaridade = 4,
                            Nome = "Silas",
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 194,
                            DataNascimento = new DateTime(2002, 5, 21, 3, 29, 29, 198, DateTimeKind.Local).AddTicks(5146),
                            Email = "manuela.nogueira@live.com",
                            Escolaridade = 2,
                            Nome = "Carlos",
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 195,
                            DataNascimento = new DateTime(2012, 5, 19, 20, 47, 14, 980, DateTimeKind.Local).AddTicks(5487),
                            Email = "nicolas.macedo@hotmail.com",
                            Escolaridade = 1,
                            Nome = "Samuel",
                            Sobrenome = "Moraes"
                        },
                        new
                        {
                            Id = 196,
                            DataNascimento = new DateTime(2015, 11, 26, 4, 58, 4, 883, DateTimeKind.Local).AddTicks(8947),
                            Email = "yasmin.carvalho31@live.com",
                            Escolaridade = 3,
                            Nome = "Margarida",
                            Sobrenome = "Melo"
                        },
                        new
                        {
                            Id = 197,
                            DataNascimento = new DateTime(2012, 2, 11, 13, 28, 19, 206, DateTimeKind.Local).AddTicks(1146),
                            Email = "marcelo_oliveira94@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Matheus",
                            Sobrenome = "Albuquerque"
                        },
                        new
                        {
                            Id = 198,
                            DataNascimento = new DateTime(2006, 11, 15, 3, 4, 46, 587, DateTimeKind.Local).AddTicks(2837),
                            Email = "felix.batista70@hotmail.com",
                            Escolaridade = 3,
                            Nome = "Benício",
                            Sobrenome = "Saraiva"
                        },
                        new
                        {
                            Id = 199,
                            DataNascimento = new DateTime(2015, 10, 28, 19, 36, 10, 592, DateTimeKind.Local).AddTicks(1527),
                            Email = "analuiza43@bol.com.br",
                            Escolaridade = 1,
                            Nome = "Esther",
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 200,
                            DataNascimento = new DateTime(2003, 11, 28, 22, 41, 26, 305, DateTimeKind.Local).AddTicks(6080),
                            Email = "marcelo53@live.com",
                            Escolaridade = 4,
                            Nome = "Danilo",
                            Sobrenome = "Saraiva"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
